import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
	variable: "--font-jetbrains-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}
			>
				<div className="min-h-screen flex flex-col">
					<main className="flex-1">{children}</main>
					<footer className="border-t py-3 text-center text-xs text-gray-600">
						Made by <a href="https://giftakis.gr" target="_blank" rel="noopener noreferrer" className="underline hover:text-black">Giftakis Ioannis</a>
					</footer>
				</div>
			</body>
		</html>
	);
}
